### ISSUE TITLE
Can't compile on Xcode 11 with Swift 5.1

### ISSUE THREAD

**Issue by aquilx** [Daimler/MBSDK-Mobile-iOS#2]
The full error information is  "Module compiled with Swift 5.1 cannot be imported by the Swift 5.0.1 compiler:..."

Xcode 11
Swift 5.1

please figure out this issue.

**Comment by mscx** [comment]
Hi @aquilx. We will have a look at this issue and provide feedback. Greetings, Marco

**Comment by suhooh** [comment]
"Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler:..." in my case.
I guess both frameworks need to be updated with one which is built with swift 5.1.

**Comment by gtatgh** [comment]
I'm getting the same error using Xcode 11.2.1 (11B500). Trying to compile [MBSDK-Example-iOS](https://github.com/Daimler/MBSDK-Example-iOS) project.

**Comment by AF-cgi** [comment]
Now the SDK is compatible to Swift 5.x.
